### ISSUE TITLE
Add client-side location validation

### ISSUE THREAD

**Issue by LoganDSPrice** [firstdraft/checkins#72]
We want to validate the location of a student when they check in.

Steps:
- Add `validations` column as `jsonb` to `Contexts` and `Resources`
- Add 'Use location for validation' checkbox to `Contexts#edit` and `Resources#edit`
- Add lat/long fields to forms on `Contexts#edit` and `Resources#edit`
- Save lat/long and `enabled?` to jsonb in `Context`
- Copy jsonb data to `context`'s resources
- Update logic for validating Attendances

PR: #80

**Comment by jelaniwoods** [comment]
@LoganDSPrice did we decide what the most User friendly way to do this is?

- Having the Instructor set a location for each resource
- Having the Instructor checkin to set the location for each meeting
- Base the location of the meeting off of the location of the majority of the checkins
